"""making some attributes nullable for easier integration

Revision ID: 923930295eb1
Revises: 5043f0adbd47
Create Date: 2025-11-22 08:54:24.339624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923930295eb1'
down_revision: Union[str, Sequence[str], None] = '5043f0adbd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'location',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'location',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
